version: '3'
services:
  server-api:
    build: backend
    env_file:
      - backend/.env
    ports:
      - 8000:8000

  front-app:
    build: frontend
    env_file:
      - frontend/.env
    ports:
      - 8080:80
    

