// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOWIFatH_Qa0xqRqJSJnFLK1KngMQ6G5g',
    appId: '1:423641214315:web:4b99afd339fe65480a302e',
    messagingSenderId: '423641214315',
    projectId: 'projet-fin-d-annee-4e30e',
    authDomain: 'projet-fin-d-annee-4e30e.firebaseapp.com',
    storageBucket: 'projet-fin-d-annee-4e30e.appspot.com',
    measurementId: 'G-QW7XB3VBR4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEoX3WqvEpWr1JxuKAI9jDi8Zn4xN6gck',
    appId: '1:423641214315:android:0fc5323c4b3d0a210a302e',
    messagingSenderId: '423641214315',
    projectId: 'projet-fin-d-annee-4e30e',
    storageBucket: 'projet-fin-d-annee-4e30e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMPCIQyn4fUBtjnGpy-1OvvB8khsyZE1Y',
    appId: '1:423641214315:ios:5cfc6b843edce57d0a302e',
    messagingSenderId: '423641214315',
    projectId: 'projet-fin-d-annee-4e30e',
    storageBucket: 'projet-fin-d-annee-4e30e.appspot.com',
    iosClientId: '423641214315-bt61ek6pv2skk4q1r218dnqubdj6hb2k.apps.googleusercontent.com',
    iosBundleId: 'com.example.meublox',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMPCIQyn4fUBtjnGpy-1OvvB8khsyZE1Y',
    appId: '1:423641214315:ios:5cfc6b843edce57d0a302e',
    messagingSenderId: '423641214315',
    projectId: 'projet-fin-d-annee-4e30e',
    storageBucket: 'projet-fin-d-annee-4e30e.appspot.com',
    iosClientId: '423641214315-bt61ek6pv2skk4q1r218dnqubdj6hb2k.apps.googleusercontent.com',
    iosBundleId: 'com.example.meublox',
  );
}
